In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
data = pd.read_excel('MCM_NFLIS_Data.xlsx',sheet_name='Data')

In [2]:
demo_2010 = pd.read_csv('ACS_10_5YR_DP02/ACS_10_5YR_DP02_with_ann.csv')
demo_2011 = pd.read_csv('ACS_11_5YR_DP02/ACS_11_5YR_DP02_with_ann.csv')
demo_2012 = pd.read_csv('ACS_12_5YR_DP02/ACS_12_5YR_DP02_with_ann.csv')
demo_2013 = pd.read_csv('ACS_13_5YR_DP02/ACS_13_5YR_DP02_with_ann.csv')
demo_2014 = pd.read_csv('ACS_14_5YR_DP02/ACS_14_5YR_DP02_with_ann.csv')
demo_2015 = pd.read_csv('ACS_15_5YR_DP02/ACS_15_5YR_DP02_with_ann.csv')
demo_2016 = pd.read_csv('ACS_16_5YR_DP02/ACS_16_5YR_DP02_with_ann.csv')

In [3]:
#creating empty dataset
for i in range(4,10):
    data["HC01_VC0"+str(i)] = np.nan
for i in range(10,110):
    data["HC01_VC"+str(i)] = np.nan

In [4]:
#merging data from 2010 to 2016
for index, row in data.iterrows():
    if row['YYYY'] == 2010:
        for i in range(4,10):
            if ("HC01_VC0"+str(i)) in demo_2010.columns:
                data.at[index, "HC01_VC0"+str(i)] = demo_2010.loc[demo_2010['GEO.id2'] == str(row['FIPS_Combined'])]["HC01_VC0"+str(i)].values[0]
        for i in range(10,220):
            try:
                if ("HC01_VC"+str(i)) in demo_2010.columns:
                    data.at[index, "HC01_VC"+str(i)] = demo_2010.loc[demo_2010['GEO.id2'] == str(row['FIPS_Combined'])]["HC01_VC"+str(i)].values[0]
            except:
                continue       
    if row['YYYY'] == 2011:
        for i in range(4,10):
            if ("HC01_VC0"+str(i)) in demo_2011.columns:
                data.at[index, "HC01_VC0"+str(i)] = demo_2011.loc[demo_2011['GEO.id2'] == str(row['FIPS_Combined'])]["HC01_VC0"+str(i)].values[0]
        for i in range(10,220):
            try:
                if ("HC01_VC"+str(i)) in demo_2011.columns:
                    data.at[index, "HC01_VC"+str(i)] = demo_2011.loc[demo_2011['GEO.id2'] == str(row['FIPS_Combined'])]["HC01_VC"+str(i)].values[0]
            except:
                continue        
    if row['YYYY'] == 2012:
        for i in range(4,10):
            if ("HC01_VC0"+str(i)) in demo_2012.columns:
                data.at[index, "HC01_VC0"+str(i)] = demo_2012.loc[demo_2012['GEO.id2'] == str(row['FIPS_Combined'])]["HC01_VC0"+str(i)].values[0]
        for i in range(10,220):
            try:
                if ("HC01_VC"+str(i)) in demo_2012.columns:
                    data.at[index, "HC01_VC"+str(i)] = demo_2012.loc[demo_2012['GEO.id2'] == str(row['FIPS_Combined'])]["HC01_VC"+str(i)].values[0]
            except:
                continue        
    if row['YYYY'] == 2013:
        for i in range(4,10):
            if ("HC01_VC0"+str(i)) in demo_2013.columns:
                data.at[index, "HC01_VC0"+str(i)] = demo_2013.loc[demo_2013['GEO.id2'] == str(row['FIPS_Combined'])]["HC01_VC0"+str(i)].values[0]
        for i in range(10,220):
            try:
                if ("HC01_VC"+str(i)) in demo_2013.columns:
                    data.at[index, "HC01_VC"+str(i)] = demo_2013.loc[demo_2013['GEO.id2'] == str(row['FIPS_Combined'])]["HC01_VC"+str(i)].values[0]
            except:
                continue        
    if row['YYYY'] == 2014:
        for i in range(4,10):
            if ("HC01_VC0"+str(i)) in demo_2014.columns:
                data.at[index, "HC01_VC0"+str(i)] = demo_2014.loc[demo_2014['GEO.id2'] == str(row['FIPS_Combined'])]["HC01_VC0"+str(i)].values[0]
        for i in range(10,220):
            try:
                if ("HC01_VC"+str(i)) in demo_2014.columns:
                    data.at[index, "HC01_VC"+str(i)] = demo_2014.loc[demo_2014['GEO.id2'] == str(row['FIPS_Combined'])]["HC01_VC"+str(i)].values[0]
            except:
                continue        
    if row['YYYY'] == 2015:
        for i in range(4,10):
            if ("HC01_VC0"+str(i)) in demo_2015.columns:
                data.at[index, "HC01_VC0"+str(i)] = demo_2015.loc[demo_2015['GEO.id2'] == str(row['FIPS_Combined'])]["HC01_VC0"+str(i)].values[0]
        for i in range(10,220):
            try:
                if ("HC01_VC"+str(i)) in demo_2015.columns:
                    data.at[index, "HC01_VC"+str(i)] = demo_2015.loc[demo_2015['GEO.id2'] == str(row['FIPS_Combined'])]["HC01_VC"+str(i)].values[0]
            except:
                continue        
    if row['YYYY'] == 2016:
        for i in range(4,10):
            if ("HC01_VC0"+str(i)) in demo_2016.columns:
                data.at[index, "HC01_VC0"+str(i)] = demo_2016.loc[demo_2016['GEO.id2'] == str(row['FIPS_Combined'])]["HC01_VC0"+str(i)].values[0]
        for i in range(10,220):
            try:
                if ("HC01_VC"+str(i)) in demo_2016.columns:
                    data.at[index, "HC01_VC"+str(i)] = demo_2016.loc[demo_2016['GEO.id2'] == str(row['FIPS_Combined'])]["HC01_VC"+str(i)].values[0]
            except:
                continue

In [5]:
data = data.drop(data.loc[data['YYYY'] == 2017].index)
data_nona = data.dropna(axis=1)
data_nona

,YYYY,State,COUNTY,FIPS_State,FIPS_County,FIPS_Combined,SubstanceName,DrugReports,TotalDrugReportsCounty,TotalDrugReportsState,...,HC01_VC200,HC01_VC201,HC01_VC202,HC01_VC203,HC01_VC204,HC01_VC205,HC01_VC206,HC01_VC207,HC01_VC208,HC01_VC209
0,2010,KY,ALLEN,21,3,21003,Oxycodone,15,168,29588,...,0,350,335,24,0,0,0,0,12,0
1,2010,KY,ALLEN,21,3,21003,Oxymorphone,1,168,29588,...,0,350,335,24,0,0,0,0,12,0
2,2010,KY,BARREN,21,9,21009,Morphine,3,383,29588,...,0,988,1509,38,35,90,39,9,182,28
3,2010,KY,BATH,21,11,21011,Buprenorphine,1,81,29588,...,0,199,273,0,0,34,17,0,99,0
4,2010,KY,BATH,21,11,21011,Hydrocodone,7,81,29588,...,0,199,273,0,0,34,17,0,99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23869,2016,WV,WOOD,54,107,54107,Morphine,4,483,5405,...,265,1245,53,163,1848,2473,128,226,336,234
23870,2016,WV,WOOD,54,107,54107,Tramadol,4,483,5405,...,265,1245,53,163,1848,2473,128,226,336,234
23871,2016,WV,TYLER,54,95,54095,Oxycodone,1,22,5405,...,76,145,0,4,319,196,7,0,36,33
23872,2016,WV,WAYNE,54,99,54099,Oxycodone,4,49,5405,...,96,225,32,19,821,1019,7,0,52,12
23873,2016,WV,WOOD,54,107,54107,Oxycodone,7,483,5405,...,265,1245,53,163,1848,2473,128,226,336,234

In [6]:
columns = data_nona.columns[10:112]
print(columns)

Index(['HC01_VC04', 'HC01_VC06', 'HC01_VC07', 'HC01_VC08', 'HC01_VC09',
       'HC01_VC10', 'HC01_VC11', 'HC01_VC12', 'HC01_VC13', 'HC01_VC14',
       ...
       'HC01_VC200', 'HC01_VC201', 'HC01_VC202', 'HC01_VC203', 'HC01_VC204',
       'HC01_VC205', 'HC01_VC206', 'HC01_VC207', 'HC01_VC208', 'HC01_VC209'],
      dtype='object', length=102)

In [7]:
data_no_feature = data_nona[['YYYY', 'State', 'SubstanceName', 'DrugReports']]
data_no_feature

       YYYY State  SubstanceName  DrugReports
0      2010    KY      Oxycodone           15
1      2010    KY    Oxymorphone            1
2      2010    KY       Morphine            3
3      2010    KY  Buprenorphine            1
4      2010    KY    Hydrocodone            7
...     ...   ...            ...          ...
23869  2016    WV       Morphine            4
23870  2016    WV       Tramadol            4
23871  2016    WV      Oxycodone            1
23872  2016    WV      Oxycodone            4
23873  2016    WV      Oxycodone            7

[20209 rows x 4 columns]

In [8]:
data_no_feature_count = data_no_feature.groupby(['YYYY', 'State', 'SubstanceName']).sum()
data_no_feature_count

                             DrugReports
YYYY State SubstanceName
2010 KY    Buprenorphine             460
           Codeine                    56
           Fentanyl                   17
           Heroin                    629
           Hydrocodone              2863
...                                  ...
2016 WV    Oxycodone                 477
           Oxymorphone               102
           Tramadol                   17
           U-47700                     2
           p-Fluorofentanyl            1

[664 rows x 1 columns]

In [9]:
from sklearn.svm import SVR
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

In [10]:
# State name choosen
# Substance name choosen
Substance_Name = 'Heroin'
State = 'OH'
Substance_no_feature = data_no_feature.loc[(data_no_feature['SubstanceName'] == Substance_Name)&(data_no_feature['State'] == State)]
Substance_no_feature_count = Heroin_no_feature.groupby(['YYYY']).sum()
Substance_no_feature_count

NameError: name 'Heroin_no_feature' is not defined

In [ ]:
X =[[2010], [2011], [2012], [2013], [2014]]
X_test = [[2010], [2011], [2012], [2013], [2014], [2015], [2016]]

In [ ]:
Y = Substance_no_feature_count['DrugReports'].values[0:5]
Y_test = Substance_no_feature_count['DrugReports'].values
print(Y)

In [ ]:
from sklearn.linear_model import Ridge
regr = Ridge()
regr.fit(X, Y)
print(f"test score:", regr.score(X_test, Y_test))

In [ ]:
Y_predicted = regr.predict(X_test)

In [ ]:
import matplotlib.pyplot as plt 
fig, ax = plt.subplots()
ax.scatter(Y_predicted, Y_test, edgecolors=(0, 0, 1))
ax.plot([Y_test.min(), Y_test.max()], [Y_test.min(), Y_test.max()], 'r--', lw=3)
ax.set_xlabel('Predicted')
ax.set_ylabel('Actual')
plt.show()

In [ ]:
# model evaluation for testing set
from sklearn import metrics

mae = metrics.mean_absolute_error(Y_test, Y_predicted)
mse = metrics.mean_squared_error(Y_test, Y_predicted)
r2 = metrics.r2_score(Y_test, Y_predicted)

print("The model performance for testing set")
print("--------------------------------------")
print('MAE is {}'.format(mae))
print('MSE is {}'.format(mse))
print('R2 score is {}'.format(r2))

In [ ]:
if Substance_Name == 'Heroin':
    feature = ['HC01_VC185','HC01_VC119','HC01_VC36','HC01_VC170','HC01_VC43','HC01_VC85','HC01_VC70','HC01_VC197','HC01_VC86','HC01_VC194']
if Substance_Name == 'Oxycodone':
    feature = ['HC01_VC46','HC01_VC200','HC01_VC11','HC01_VC192','HC01_VC91','HC01_VC47','HC01_VC40','HC01_VC198','HC01_VC67','HC01_VC86']
if Substance_Name == 'Hydrocodone':
    feature = ['HC01_VC196','HC01_VC40','HC01_VC192','HC01_VC200','HC01_VC67','HC01_VC47','HC01_VC194','HC01_VC91','HC01_VC198','HC01_VC86']
if Substance_Name == 'Fentanyl':
    feature = ['HC01_VC46','HC01_VC07','HC01_VC27','HC01_VC89','HC01_VC12','HC01_VC132','HC01_VC28','HC01_VC171','HC01_VC122','HC01_VC133']
if Substance_Name == 'Buprenorphine':
    feature = ['HC01_VC30','HC01_VC200','HC01_VC10','HC01_VC187','HC01_VC37','HC01_VC189','HC01_VC47','HC01_VC44','HC01_VC86','HC01_VC186']

In [ ]:
if State == 'OH':
    population = 11536504
if State == 'PA':
    population = 12702379
if State == 'VA':
    population = 8001024
if State == 'KY':
    population = 4339333
if State == 'WV':
    population = 1852994

In [ ]:
X_new =[[2010], [2011], [2012], [2013], [2014]]
X_test_new = [[2010], [2011], [2012], [2013], [2014], [2015], [2016]]

In [ ]:
# Heroine_feature
feature_count = data_nona.loc[(data_nona['YYYY'] == 2010) & (data_nona['State'] == State) & (data_nona['SubstanceName'] == Substance_Name), 'HC01_VC185'].astype(int).sum()

In [ ]:
feature_count

In [ ]:
for item in feature:
    for i in range(0,5):
        feature_count = data_nona.loc[(data_nona['YYYY'] == int('201'+str(i))) & (data_nona['State'] == State) & (data_nona['SubstanceName'] == Substance_Name), item].astype(int).sum()
        X_new[i].append(feature_count/population)
        X_test_new[i].append(feature_count/population)
    for i in range(5,7):
        feature_count = data_nona.loc[(data_nona['YYYY'] == int('201'+str(i))) & (data_nona['State'] == State) & (data_nona['SubstanceName'] == Substance_Name), item].astype(int).sum()
        X_test_new[i].append(feature_count/population)

In [ ]:
print(X_new)

In [ ]:
regr = Ridge()
regr.fit(X_new, Y)
print(f"test score:", regr.score(X_test_new, Y_test))

In [ ]:
Y_predicted = regr.predict(X_test_new)

In [ ]:
import matplotlib.pyplot as plt 
fig, ax = plt.subplots()
ax.scatter(Y_predicted, Y_test, edgecolors=(0, 0, 1))
ax.plot([Y_test.min(), Y_test.max()], [Y_test.min(), Y_test.max()], 'r--', lw=3)
ax.set_xlabel('Predicted')
ax.set_ylabel('Actual')
plt.show()

In [ ]:
mae = metrics.mean_absolute_error(Y_test, Y_predicted)
mse = metrics.mean_squared_error(Y_test, Y_predicted)
r2 = metrics.r2_score(Y_test, Y_predicted)

print("The model performance for testing set")
print("--------------------------------------")
print('MAE is {}'.format(mae))
print('MSE is {}'.format(mse))
print('R2 score is {}'.format(r2))